var dataProduct= [
    {
        id:1,
        name:"WD 2TB Elements",
        type:"electronics",
        vote:3.4,
        img: "./img/product.jpg",
        price:"$64",
    },
    {
        id:2,
        name:"WD 2TB Elements",
        type:"electronics",
        vote:3.4,
        img: "./img/product.jpg",
        price:"$64",
    },
    {
        id:3,
        name:"WD 2TB Elements",
        type:"electronics",
        vote:3.4,
        img: "./img/product.jpg",
        price:"$64",
    },
    {
        id:4,
        name:"WD 2TB Elements",
        type:"electronics",
        vote:3.4,
        img: "./img/product.jpg",
        price:"$64",
    },
    {
        id:5,
        name:"WD 2TB Elements",
        type:"electronics",
        vote:3.4,
        img: "./img/product.jpg",
        price:"$64",
    },
    {
        id:6,
        name:"WD 2TB Elements",
        type:"electronics",
        vote:3.4,
        img: "./img/product.jpg",
        price:"$64",
    },
]
