<<<<<<< HEAD
import "./globals.css"
=======
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

>>>>>>> a7a5c9e109c18f3d67315a859f86fd3070dfcd80
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

<<<<<<< HEAD
import "@fortawesome/fontawesome-svg-core/styles.css"; // import Font Awesome CSS
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
=======
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
>>>>>>> a7a5c9e109c18f3d67315a859f86fd3070dfcd80
    </html>
  )
}
