import { NextAuthProvider } from "./components/Provider";
// import { NextUIProvider } from "@nextui-org/react";
// import { ThemeProvider } from "next-themes";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
